name = "eletrize-template"
main = "functions/hubitat-proxy.js"
compatibility_date = "2026-04-29"
workers_dev = true

# Build configuration
[build]
command = ""
cwd = ""
watch_paths = []


# Variáveis de ambiente
[env.production]
name = "eletrize-template-prod"
vars = { ENVIRONMENT = "production" }

[env.development]
name = "eletrize-template-dev"
vars = { ENVIRONMENT = "development" }
